### ISSUE TITLE
Bug Api

### ISSUE THREAD

**Issue by MaximeChallon** [MaximeChallon/InventaireParisHistorique#58]
2021-01-14 04:23:00,924: Exception on /api/photographie/adresse [GET] Traceback (most recent call last): File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise raise value File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/ParisHistoriqueInventaire/InventaireParisHistorique/app/routes/api.py", line 86, in recherche_photo_adresse N_rue = str(adresse_parser.parse(recherche)["numero"]) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/AdresseParser/AdresseParser.py", line 27, in parse bloc_rue, bloc_ville = self.blocs(adresse_string) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/AdresseParser/AdresseParser.py", line 63, in blocs if re.match("^[0-9]{5}[a-zA-Z éèàùêôî-]{0,}[0-9]{1,4}(.+)$", adresse_string): File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/re.py", line 173, in match return _compile(pattern, flags).match(string)

**Comment by MaximeChallon** [comment]
2021-01-16 22:59:00,526: Exception on /api/photographie/numeros_inventaire [GET] Traceback (most recent call last): File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise raise value File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/ParisHistoriqueInventaire/InventaireParisHistorique/app/routes/api.py", line 58, in multiple_photo_id _from = str(re.sub("[^0-9]+[0-9]+$", "", recherche)) File "/home/ParisHistoriqueInventaire/.virtualenvs/env/lib/python3.7/re.py", line 192, in sub return _compile(pattern, flags).sub(repl, string, count) TypeError: expected string or bytes-like object
